

baseURL = "https://okimurak.github.io"
languageCode = "en-us"
DefaultContentLanguage = "ja"
title = "٩( ‘ω’ )و"
theme = "anatole"
summarylength = 1
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "okky"
author = "okimurak | okky"
description = "Cloud Engineer"
profilePicture = "images/profile.jpeg"
keywords = "AWS"
favicon = "favicons/"
customCss = ["css/custom.css"]
customJs = []
mainSections = ["blog"]
images = ["images/site-feature-image.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/okky_eng"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/okimurak/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/okimurak"

[[params.socialIcons]]
icon = "icon-qiita"
title = "Qiita"
url = "https://qiita.com/okky_eng"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blogs"
  weight = 200
  identifier = "blogs"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
