version: "3.3"

services:
  web:
    image: jguyomard/hugo-builder
    container_name: hugo
    ports:
      - "1313:1313"
    volumes:
      - ./:/usr/local/okimurak/okimurak-github-io
    working_dir: /usr/local/okimurak/okimurak-github-io
    command: hugo server --bind 0.0.0.0
